import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header>
          {/* <form>
            <button formAction={signOut}>Logout</button>
            <button formAction={refreshSession}>refresh token</button>
          </form> */}

          <div>
            <Link href="/sign-in">Sign In</Link>
            <Link href="/sign-up">Sign Up</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}

// async function signOut() {
//   'use server';
//   await supabase().auth.signOut();
//   revalidatePath('/');
// }

// async function refreshSession() {
//   'use server';
//   const session = await supabase()
//     .auth.refreshSession()
//     .then((r) => r.data.session);
//   if (session) await supabase().auth.setSession(session);
//   revalidatePath('/');
// }
